#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# eFlows4HPC documentation build configuration file, created by
# sphinx-quickstart on Thu Oct  3 13:27:53 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.imgmath',
              'sphinx.ext.ifconfig',
              'sphinx.ext.imgconverter',
              'sphinx.ext.viewcode',
              'sphinx.ext.githubpages',
              'sphinx.ext.autosectionlabel',
              'sphinx.ext.mathjax',
              'sphinxcontrib.contentui',
              'nbsphinx',
              'sphinx_copybutton',
              'sphinxcontrib.bibtex',
              'sphinxcontrib.yt']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'eFlows4HPC'
copyright = 'eFlows4HPC Consortium'
author = ' Jorge Ejarque (BSC)' # Add here other contributors

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0'
# The full version, including alpha/beta/rc tags.
release = '220'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', '**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default' # 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# True to prefix each section label with the name of the document it is in,
# followed by a colon.
autosectionlabel_prefix_document = True

# Specific configuration
numfig = True
numfig_secnum_depth = 0
numfig_format = {'figure':'Figure %s',
                 'table':'Table %s',
                 'code-block':'Code %s',
                 'section':'Section %s'}
html_permalinks = False  # Disabled permalinks
html_logo = './Logos/icono_linial.png'
html_favicon = './Logos/icono_color.png'
html_show_sourcelink = False
html_show_copyright = False
html_show_sphinx = True 
nitpicky = True
latex_logo = './Logos/Color.png'

# Disabe notebooks Building
nbsphinx_execute = 'never'
nbsphinx_execute_arguments = [
    "--InlineBackend.figure_formats={'svg', 'pdf'}",
    "--InlineBackend.rc={'figure.dpi': 96}",
]
# Do not allow building if execution is enabled and a notebook fails
nbsphinx_allow_errors = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme' # 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {'logo_only': True,
                      'navigation_depth': 8}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']
#
# html_context = {
#     'css_files': ['_static/_theme_overrides.css',  # override wide tables in RTD theme
#                  ],
# }

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'relations.html',  # needs 'show_related': True theme option to display
        'searchbox.html',
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'eflows4HPCdoc'

html_scaled_image_link = False

# -- Options for LaTeX output ---------------------------------------------
latex_engine = 'pdflatex'
latex_additional_files = ['./Logos/*']
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',
    'releasename':" ",
    # Sonny, Lenny, Glenn, Conny, Rejne, Bjarne and Bjornstrup
    # 'fncychap': '\\usepackage[Lenny]{fncychap}',
    'fncychap': '\\usepackage{fncychap}',
    'fontpkg': '\\usepackage{amsmath,amsfonts,amssymb,amsthm}',

    'figure_align':'htbp',
    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    'preamble': r'''
        %%%%%%%%%%%%%%%%%%%% PREAMBLE %%%%%%%%%%%%%%%%%%
        %%% Add number to subsubsection 2=subsection, 3=subsubsection
        %%% Below subsubsection is not good idea.
        \setcounter{secnumdepth}{3}

        %%% Table of content upto 2=subsection, 3=subsubsection
        \setcounter{tocdepth}{2}

        %%% Load packages
        \usepackage{amsmath,amsfonts,amssymb,amsthm}
        \usepackage{graphicx}
        \usepackage[strings]{underscore}

        %%% Reduce spaces for Table of contents, figures and tables-
        %%% It is used "\addtocontents{toc}{\vskip -1.2cm}" etc. in the document
        \usepackage[notlot,nottoc,notlof]{}

        \usepackage{color}
        \usepackage{transparent}
        \usepackage{eso-pic}
        \usepackage{lipsum}

        %%% Link at the footnote to go to the place of footnote in the text
        \usepackage{footnotebackref}
        \makeatletter
        \LetLtxMacro{\BHFN@Old@footnotemark}{\@footnotemark}

        \renewcommand*{\@footnotemark}{%
            \refstepcounter{BackrefHyperFootnoteCounter}%
            \xdef\BackrefFootnoteTag{bhfn:\theBackrefHyperFootnoteCounter}%
            \label{\BackrefFootnoteTag}%
            \BHFN@Old@footnotemark
        }
        \makeatother

        %%% Spacing between line
        \usepackage{setspace}
        %%%% \onehalfspacing
        %%%% \doublespacing
        \singlespacing

        %%% Datetime
        \usepackage{datetime}
        \newdateformat{MonthYearFormat}{%
            \monthname[\THEMONTH], \THEYEAR}

        %% RO, LE will not work for 'oneside' layout.
        %% Change oneside to twoside in document class
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}

        %%% Alternating Header for oneside
        \fancyhead[L]{\ifthenelse{\isodd{\value{page}}}{ \small \nouppercase{\leftmark} }{}}
        \fancyhead[R]{\ifthenelse{\isodd{\value{page}}}{}{ \small \nouppercase{\rightmark} }}

        %%% Alternating Header for two side
        %\fancyhead[RO]{\small \nouppercase{\rightmark}}
        %\fancyhead[LE]{\small \nouppercase{\leftmark}}

        %%% For oneside: change footer at right side. If you want to use Left and right then use same as header defined above.
        \fancyfoot[R]{\ifthenelse{\isodd{\value{page}}}{{\tiny eFlows4HPC Consortium} }{\href{https://eflows4hpc.es}{}}}

        %%% Alternating Footer for two side
        %\fancyfoot[RO, RE]{\scriptsize eFlows4HPC Consortium}

        %%% page number
        \fancyfoot[CO, CE]{\thepage}

        \renewcommand{\headrulewidth}{0.5pt}
        \renewcommand{\footrulewidth}{0.5pt}

        \RequirePackage{tocbibind} %%% comment this to remove page number for following
        \addto\captionsenglish{\renewcommand{\contentsname}{Table of contents}}
        \addto\captionsenglish{\renewcommand{\listfigurename}{List of figures}}
        \addto\captionsenglish{\renewcommand{\listtablename}{List of tables}}
        % \addto\captionsenglish{\renewcommand{\chaptername}{Chapter}}

        %%% Reduce spacing for itemize
        \usepackage{enumitem}
        \setlist{nosep}

        %%% Quote Styles at the top of chapter
        \usepackage{epigraph}
        \setlength{\epigraphwidth}{0.8\columnwidth}
        \newcommand{\chapterquote}[2]{\epigraphhead[60]{\epigraph{\textit{#1}}{\textbf {\textit{--#2}}}}}
        %%% Quote for all places except Chapter
        \newcommand{\sectionquote}[2]{{\quote{\textit{``#1''}}{\textbf {\textit{--#2}}}}}

        %%%%%%%%%%%%%%%%%% END PREAMBLE %%%%%%%%%%%%%%%%%
    ''',

    'maketitle': r'''
        \pagenumbering{Roman} %%% to avoid page 1 conflict with actual page 1

        \begin{titlepage}
            \centering

            \vspace*{40mm} %%% * is used to give space from top
            %%% \textbf{\Huge {Title over the logo}}

            \vspace{0mm}
            \begin{figure}[!h]
             \centering
             \includegraphics[scale=1]{Color_Full.png}
            \end{figure}

            \vspace{0mm}
            \Huge \textbf{{eFlows4HPC Documentation}}

            \Large eFlows4HPC Consortium
            \vspace{0mm}

            \vspace*{20mm}
            \large  Last updated : \MonthYearFormat\today

            %% \vfill adds at the bottom
            \vfill
            \normalsize \textit{Online version available at }{\href{https://eflows4hpc.readthedocs.io/en/latest/}{eFlows4HPC - ReadTheDocs}}
        \end{titlepage}

        \clearpage
        \pagenumbering{roman}
        \tableofcontents
        \listoffigures
        \listoftables
        \clearpage
        \pagenumbering{arabic}

        ''',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    'sphinxsetup': \
        'hmargin={0.7in,0.7in}, vmargin={1in,1in}, \
        verbatimwithframe=true, \
        TitleColor={rgb}{0,0,0}, \
        HeaderFamily=\\rmfamily\\bfseries, \
        InnerLinkColor={rgb}{0,0,1}, \
        OuterLinkColor={rgb}{0,0,1}',

        'tableofcontents':' ',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'eflows4hpc.tex', 'eFlows4HPC Documentation',
     'eFlows4HPC Consortion', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'eflows4hpc', 'eFlows4HPC Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'eFlows4HPC', 'eFlows4HPC Documentation',
     author, 'eFlows4HPC', 'eFlows4HPC Manuals.',
     'Software Release'),
]
